//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCT_GIA_DINH.GD_Service {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GD_Service.GiaDinhServiceSoap")]
    public interface GiaDinhServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Them_Khoan_chi_Gia_dinh", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Them_Khoan_chi_Gia_dinh(string ID, string Ngay, string So_tien, string ID_Gia_dinh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Them_Khoan_chi_Gia_dinh", ReplyAction="*")]
        System.Threading.Tasks.Task Them_Khoan_chi_Gia_dinhAsync(string ID, string Ngay, string So_tien, string ID_Gia_dinh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Xoa_Khoan_chi_Gia_dinh", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Xoa_Khoan_chi_Gia_dinh(string ID, string ID_Gia_dinh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Xoa_Khoan_chi_Gia_dinh", ReplyAction="*")]
        System.Threading.Tasks.Task Xoa_Khoan_chi_Gia_dinhAsync(string ID, string ID_Gia_dinh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Cap_nhat_Khoan_chi_Gia_dinh", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Cap_nhat_Khoan_chi_Gia_dinh(string ID, string Ngay, string So_tien, string ID_Gia_dinh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Cap_nhat_Khoan_chi_Gia_dinh", ReplyAction="*")]
        System.Threading.Tasks.Task Cap_nhat_Khoan_chi_Gia_dinhAsync(string ID, string Ngay, string So_tien, string ID_Gia_dinh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ID_Khoan_chi_Gia_dinh_Tu_tang", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ID_Khoan_chi_Gia_dinh_Tu_tang();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ID_Khoan_chi_Gia_dinh_Tu_tang", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ID_Khoan_chi_Gia_dinh_Tu_tangAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Them_Khoan_thu_Gia_dinh", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Them_Khoan_thu_Gia_dinh(string ID, string Ngay, string So_tien, string ID_Gia_dinh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Them_Khoan_thu_Gia_dinh", ReplyAction="*")]
        System.Threading.Tasks.Task Them_Khoan_thu_Gia_dinhAsync(string ID, string Ngay, string So_tien, string ID_Gia_dinh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Xoa_Khoan_thu_Gia_dinh", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Xoa_Khoan_thu_Gia_dinh(string ID, string ID_Gia_dinh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Xoa_Khoan_thu_Gia_dinh", ReplyAction="*")]
        System.Threading.Tasks.Task Xoa_Khoan_thu_Gia_dinhAsync(string ID, string ID_Gia_dinh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Cap_nhat_Khoan_thu_Gia_dinh", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Cap_nhat_Khoan_thu_Gia_dinh(string ID, string Ngay, string So_tien, string ID_Gia_dinh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Cap_nhat_Khoan_thu_Gia_dinh", ReplyAction="*")]
        System.Threading.Tasks.Task Cap_nhat_Khoan_thu_Gia_dinhAsync(string ID, string Ngay, string So_tien, string ID_Gia_dinh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ID_Khoan_thu_Gia_dinh_Tu_tang", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ID_Khoan_thu_Gia_dinh_Tu_tang();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ID_Khoan_thu_Gia_dinh_Tu_tang", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ID_Khoan_thu_Gia_dinh_Tu_tangAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Them_Khoan_chi_Thanh_vien", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Them_Khoan_chi_Thanh_vien(string ID, string Ngay, string So_tien, string ID_Thanh_vien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Them_Khoan_chi_Thanh_vien", ReplyAction="*")]
        System.Threading.Tasks.Task Them_Khoan_chi_Thanh_vienAsync(string ID, string Ngay, string So_tien, string ID_Thanh_vien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Xoa_Khoan_chi_Thanh_vien", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Xoa_Khoan_chi_Thanh_vien(string ID, string ID_Thanh_vien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Xoa_Khoan_chi_Thanh_vien", ReplyAction="*")]
        System.Threading.Tasks.Task Xoa_Khoan_chi_Thanh_vienAsync(string ID, string ID_Thanh_vien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Cap_nhat_Khoan_chi_Thanh_vien", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Cap_nhat_Khoan_chi_Thanh_vien(string ID, string Ngay, string So_tien, string ID_Thanh_vien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Cap_nhat_Khoan_chi_Thanh_vien", ReplyAction="*")]
        System.Threading.Tasks.Task Cap_nhat_Khoan_chi_Thanh_vienAsync(string ID, string Ngay, string So_tien, string ID_Thanh_vien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ID_Khoan_chi_Thanh_vien_Tu_tang", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ID_Khoan_chi_Thanh_vien_Tu_tang();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ID_Khoan_chi_Thanh_vien_Tu_tang", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ID_Khoan_chi_Thanh_vien_Tu_tangAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Them_Khoan_thu_Thanh_vien", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Them_Khoan_thu_Thanh_vien(string ID, string Ngay, string So_tien, string ID_Thanh_vien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Them_Khoan_thu_Thanh_vien", ReplyAction="*")]
        System.Threading.Tasks.Task Them_Khoan_thu_Thanh_vienAsync(string ID, string Ngay, string So_tien, string ID_Thanh_vien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Xoa_Khoan_thu_Thanh_vien", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Xoa_Khoan_thu_Thanh_vien(string ID, string ID_Thanh_vien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Xoa_Khoan_thu_Thanh_vien", ReplyAction="*")]
        System.Threading.Tasks.Task Xoa_Khoan_thu_Thanh_vienAsync(string ID, string ID_Thanh_vien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Cap_nhat_Khoan_thu_Thanh_vien", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Cap_nhat_Khoan_thu_Thanh_vien(string ID, string Ngay, string So_tien, string ID_Thanh_vien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Cap_nhat_Khoan_thu_Thanh_vien", ReplyAction="*")]
        System.Threading.Tasks.Task Cap_nhat_Khoan_thu_Thanh_vienAsync(string ID, string Ngay, string So_tien, string ID_Thanh_vien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ID_Khoan_thu_Thanh_vien", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ID_Khoan_thu_Thanh_vien();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ID_Khoan_thu_Thanh_vien", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ID_Khoan_thu_Thanh_vienAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Lay_Ten_Thanh_vien", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Lay_Ten_Thanh_vien(string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Lay_Ten_Thanh_vien", ReplyAction="*")]
        System.Threading.Tasks.Task<string> Lay_Ten_Thanh_vienAsync(string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Lay_ID_Thanh_vien", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Lay_ID_Thanh_vien(string Ten_Thanh_vien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Lay_ID_Thanh_vien", ReplyAction="*")]
        System.Threading.Tasks.Task<string> Lay_ID_Thanh_vienAsync(string Ten_Thanh_vien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Lay_Ten_Tat_ca_Thanh_vien", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] Lay_Ten_Tat_ca_Thanh_vien();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Lay_Ten_Tat_ca_Thanh_vien", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> Lay_Ten_Tat_ca_Thanh_vienAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Lay_Ten_Va_Ngay_sinh", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] Lay_Ten_Va_Ngay_sinh(string Ten_Thanh_vien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Lay_Ten_Va_Ngay_sinh", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> Lay_Ten_Va_Ngay_sinhAsync(string Ten_Thanh_vien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Tao_bang_Quan_ly_Chi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Tao_bang_Quan_ly_Chi();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Tao_bang_Quan_ly_Chi", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Tao_bang_Quan_ly_ChiAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Tao_bang_Quan_ly_Thu", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Tao_bang_Quan_ly_Thu();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Tao_bang_Quan_ly_Thu", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Tao_bang_Quan_ly_ThuAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Tra_cuu_Thu_Chi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Tra_cuu_Thu_Chi(string Ten, string Ngay, string So_tien, string Loai_Thu_Chi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Tra_cuu_Thu_Chi", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Tra_cuu_Thu_ChiAsync(string Ten, string Ngay, string So_tien, string Loai_Thu_Chi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Lay_Tat_ca_Cac_Nam", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int[] Lay_Tat_ca_Cac_Nam();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Lay_Tat_ca_Cac_Nam", ReplyAction="*")]
        System.Threading.Tasks.Task<int[]> Lay_Tat_ca_Cac_NamAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Thong_ke_Tong_Quat", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int[] Thong_ke_Tong_Quat(string Thang, string Nam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Thong_ke_Tong_Quat", ReplyAction="*")]
        System.Threading.Tasks.Task<int[]> Thong_ke_Tong_QuatAsync(string Thang, string Nam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Lay_danh_Sach_Ten", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] Lay_danh_Sach_Ten();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Lay_danh_Sach_Ten", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> Lay_danh_Sach_TenAsync();
        
        // CODEGEN: Parameter 'Lay_AnhResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Lay_Anh", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        QLCT_GIA_DINH.GD_Service.Lay_AnhResponse Lay_Anh(QLCT_GIA_DINH.GD_Service.Lay_AnhRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Lay_Anh", ReplyAction="*")]
        System.Threading.Tasks.Task<QLCT_GIA_DINH.GD_Service.Lay_AnhResponse> Lay_AnhAsync(QLCT_GIA_DINH.GD_Service.Lay_AnhRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ID_Gia_dinh_Tu_tang", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ID_Gia_dinh_Tu_tang();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ID_Gia_dinh_Tu_tang", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ID_Gia_dinh_Tu_tangAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Lay_ID_Gia_dinh", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Lay_ID_Gia_dinh(string Ten_Gia_dinh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Lay_ID_Gia_dinh", ReplyAction="*")]
        System.Threading.Tasks.Task<string> Lay_ID_Gia_dinhAsync(string Ten_Gia_dinh);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Lay_Anh", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Lay_AnhRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Ten_Hinh_anh;
        
        public Lay_AnhRequest() {
        }
        
        public Lay_AnhRequest(string Ten_Hinh_anh) {
            this.Ten_Hinh_anh = Ten_Hinh_anh;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Lay_AnhResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Lay_AnhResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Lay_AnhResult;
        
        public Lay_AnhResponse() {
        }
        
        public Lay_AnhResponse(byte[] Lay_AnhResult) {
            this.Lay_AnhResult = Lay_AnhResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GiaDinhServiceSoapChannel : QLCT_GIA_DINH.GD_Service.GiaDinhServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GiaDinhServiceSoapClient : System.ServiceModel.ClientBase<QLCT_GIA_DINH.GD_Service.GiaDinhServiceSoap>, QLCT_GIA_DINH.GD_Service.GiaDinhServiceSoap {
        
        public GiaDinhServiceSoapClient() {
        }
        
        public GiaDinhServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GiaDinhServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GiaDinhServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GiaDinhServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Them_Khoan_chi_Gia_dinh(string ID, string Ngay, string So_tien, string ID_Gia_dinh) {
            base.Channel.Them_Khoan_chi_Gia_dinh(ID, Ngay, So_tien, ID_Gia_dinh);
        }
        
        public System.Threading.Tasks.Task Them_Khoan_chi_Gia_dinhAsync(string ID, string Ngay, string So_tien, string ID_Gia_dinh) {
            return base.Channel.Them_Khoan_chi_Gia_dinhAsync(ID, Ngay, So_tien, ID_Gia_dinh);
        }
        
        public void Xoa_Khoan_chi_Gia_dinh(string ID, string ID_Gia_dinh) {
            base.Channel.Xoa_Khoan_chi_Gia_dinh(ID, ID_Gia_dinh);
        }
        
        public System.Threading.Tasks.Task Xoa_Khoan_chi_Gia_dinhAsync(string ID, string ID_Gia_dinh) {
            return base.Channel.Xoa_Khoan_chi_Gia_dinhAsync(ID, ID_Gia_dinh);
        }
        
        public void Cap_nhat_Khoan_chi_Gia_dinh(string ID, string Ngay, string So_tien, string ID_Gia_dinh) {
            base.Channel.Cap_nhat_Khoan_chi_Gia_dinh(ID, Ngay, So_tien, ID_Gia_dinh);
        }
        
        public System.Threading.Tasks.Task Cap_nhat_Khoan_chi_Gia_dinhAsync(string ID, string Ngay, string So_tien, string ID_Gia_dinh) {
            return base.Channel.Cap_nhat_Khoan_chi_Gia_dinhAsync(ID, Ngay, So_tien, ID_Gia_dinh);
        }
        
        public int ID_Khoan_chi_Gia_dinh_Tu_tang() {
            return base.Channel.ID_Khoan_chi_Gia_dinh_Tu_tang();
        }
        
        public System.Threading.Tasks.Task<int> ID_Khoan_chi_Gia_dinh_Tu_tangAsync() {
            return base.Channel.ID_Khoan_chi_Gia_dinh_Tu_tangAsync();
        }
        
        public void Them_Khoan_thu_Gia_dinh(string ID, string Ngay, string So_tien, string ID_Gia_dinh) {
            base.Channel.Them_Khoan_thu_Gia_dinh(ID, Ngay, So_tien, ID_Gia_dinh);
        }
        
        public System.Threading.Tasks.Task Them_Khoan_thu_Gia_dinhAsync(string ID, string Ngay, string So_tien, string ID_Gia_dinh) {
            return base.Channel.Them_Khoan_thu_Gia_dinhAsync(ID, Ngay, So_tien, ID_Gia_dinh);
        }
        
        public void Xoa_Khoan_thu_Gia_dinh(string ID, string ID_Gia_dinh) {
            base.Channel.Xoa_Khoan_thu_Gia_dinh(ID, ID_Gia_dinh);
        }
        
        public System.Threading.Tasks.Task Xoa_Khoan_thu_Gia_dinhAsync(string ID, string ID_Gia_dinh) {
            return base.Channel.Xoa_Khoan_thu_Gia_dinhAsync(ID, ID_Gia_dinh);
        }
        
        public void Cap_nhat_Khoan_thu_Gia_dinh(string ID, string Ngay, string So_tien, string ID_Gia_dinh) {
            base.Channel.Cap_nhat_Khoan_thu_Gia_dinh(ID, Ngay, So_tien, ID_Gia_dinh);
        }
        
        public System.Threading.Tasks.Task Cap_nhat_Khoan_thu_Gia_dinhAsync(string ID, string Ngay, string So_tien, string ID_Gia_dinh) {
            return base.Channel.Cap_nhat_Khoan_thu_Gia_dinhAsync(ID, Ngay, So_tien, ID_Gia_dinh);
        }
        
        public int ID_Khoan_thu_Gia_dinh_Tu_tang() {
            return base.Channel.ID_Khoan_thu_Gia_dinh_Tu_tang();
        }
        
        public System.Threading.Tasks.Task<int> ID_Khoan_thu_Gia_dinh_Tu_tangAsync() {
            return base.Channel.ID_Khoan_thu_Gia_dinh_Tu_tangAsync();
        }
        
        public void Them_Khoan_chi_Thanh_vien(string ID, string Ngay, string So_tien, string ID_Thanh_vien) {
            base.Channel.Them_Khoan_chi_Thanh_vien(ID, Ngay, So_tien, ID_Thanh_vien);
        }
        
        public System.Threading.Tasks.Task Them_Khoan_chi_Thanh_vienAsync(string ID, string Ngay, string So_tien, string ID_Thanh_vien) {
            return base.Channel.Them_Khoan_chi_Thanh_vienAsync(ID, Ngay, So_tien, ID_Thanh_vien);
        }
        
        public void Xoa_Khoan_chi_Thanh_vien(string ID, string ID_Thanh_vien) {
            base.Channel.Xoa_Khoan_chi_Thanh_vien(ID, ID_Thanh_vien);
        }
        
        public System.Threading.Tasks.Task Xoa_Khoan_chi_Thanh_vienAsync(string ID, string ID_Thanh_vien) {
            return base.Channel.Xoa_Khoan_chi_Thanh_vienAsync(ID, ID_Thanh_vien);
        }
        
        public void Cap_nhat_Khoan_chi_Thanh_vien(string ID, string Ngay, string So_tien, string ID_Thanh_vien) {
            base.Channel.Cap_nhat_Khoan_chi_Thanh_vien(ID, Ngay, So_tien, ID_Thanh_vien);
        }
        
        public System.Threading.Tasks.Task Cap_nhat_Khoan_chi_Thanh_vienAsync(string ID, string Ngay, string So_tien, string ID_Thanh_vien) {
            return base.Channel.Cap_nhat_Khoan_chi_Thanh_vienAsync(ID, Ngay, So_tien, ID_Thanh_vien);
        }
        
        public int ID_Khoan_chi_Thanh_vien_Tu_tang() {
            return base.Channel.ID_Khoan_chi_Thanh_vien_Tu_tang();
        }
        
        public System.Threading.Tasks.Task<int> ID_Khoan_chi_Thanh_vien_Tu_tangAsync() {
            return base.Channel.ID_Khoan_chi_Thanh_vien_Tu_tangAsync();
        }
        
        public void Them_Khoan_thu_Thanh_vien(string ID, string Ngay, string So_tien, string ID_Thanh_vien) {
            base.Channel.Them_Khoan_thu_Thanh_vien(ID, Ngay, So_tien, ID_Thanh_vien);
        }
        
        public System.Threading.Tasks.Task Them_Khoan_thu_Thanh_vienAsync(string ID, string Ngay, string So_tien, string ID_Thanh_vien) {
            return base.Channel.Them_Khoan_thu_Thanh_vienAsync(ID, Ngay, So_tien, ID_Thanh_vien);
        }
        
        public void Xoa_Khoan_thu_Thanh_vien(string ID, string ID_Thanh_vien) {
            base.Channel.Xoa_Khoan_thu_Thanh_vien(ID, ID_Thanh_vien);
        }
        
        public System.Threading.Tasks.Task Xoa_Khoan_thu_Thanh_vienAsync(string ID, string ID_Thanh_vien) {
            return base.Channel.Xoa_Khoan_thu_Thanh_vienAsync(ID, ID_Thanh_vien);
        }
        
        public void Cap_nhat_Khoan_thu_Thanh_vien(string ID, string Ngay, string So_tien, string ID_Thanh_vien) {
            base.Channel.Cap_nhat_Khoan_thu_Thanh_vien(ID, Ngay, So_tien, ID_Thanh_vien);
        }
        
        public System.Threading.Tasks.Task Cap_nhat_Khoan_thu_Thanh_vienAsync(string ID, string Ngay, string So_tien, string ID_Thanh_vien) {
            return base.Channel.Cap_nhat_Khoan_thu_Thanh_vienAsync(ID, Ngay, So_tien, ID_Thanh_vien);
        }
        
        public int ID_Khoan_thu_Thanh_vien() {
            return base.Channel.ID_Khoan_thu_Thanh_vien();
        }
        
        public System.Threading.Tasks.Task<int> ID_Khoan_thu_Thanh_vienAsync() {
            return base.Channel.ID_Khoan_thu_Thanh_vienAsync();
        }
        
        public string Lay_Ten_Thanh_vien(string ID) {
            return base.Channel.Lay_Ten_Thanh_vien(ID);
        }
        
        public System.Threading.Tasks.Task<string> Lay_Ten_Thanh_vienAsync(string ID) {
            return base.Channel.Lay_Ten_Thanh_vienAsync(ID);
        }
        
        public string Lay_ID_Thanh_vien(string Ten_Thanh_vien) {
            return base.Channel.Lay_ID_Thanh_vien(Ten_Thanh_vien);
        }
        
        public System.Threading.Tasks.Task<string> Lay_ID_Thanh_vienAsync(string Ten_Thanh_vien) {
            return base.Channel.Lay_ID_Thanh_vienAsync(Ten_Thanh_vien);
        }
        
        public string[] Lay_Ten_Tat_ca_Thanh_vien() {
            return base.Channel.Lay_Ten_Tat_ca_Thanh_vien();
        }
        
        public System.Threading.Tasks.Task<string[]> Lay_Ten_Tat_ca_Thanh_vienAsync() {
            return base.Channel.Lay_Ten_Tat_ca_Thanh_vienAsync();
        }
        
        public string[] Lay_Ten_Va_Ngay_sinh(string Ten_Thanh_vien) {
            return base.Channel.Lay_Ten_Va_Ngay_sinh(Ten_Thanh_vien);
        }
        
        public System.Threading.Tasks.Task<string[]> Lay_Ten_Va_Ngay_sinhAsync(string Ten_Thanh_vien) {
            return base.Channel.Lay_Ten_Va_Ngay_sinhAsync(Ten_Thanh_vien);
        }
        
        public System.Data.DataSet Tao_bang_Quan_ly_Chi() {
            return base.Channel.Tao_bang_Quan_ly_Chi();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Tao_bang_Quan_ly_ChiAsync() {
            return base.Channel.Tao_bang_Quan_ly_ChiAsync();
        }
        
        public System.Data.DataSet Tao_bang_Quan_ly_Thu() {
            return base.Channel.Tao_bang_Quan_ly_Thu();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Tao_bang_Quan_ly_ThuAsync() {
            return base.Channel.Tao_bang_Quan_ly_ThuAsync();
        }
        
        public System.Data.DataSet Tra_cuu_Thu_Chi(string Ten, string Ngay, string So_tien, string Loai_Thu_Chi) {
            return base.Channel.Tra_cuu_Thu_Chi(Ten, Ngay, So_tien, Loai_Thu_Chi);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Tra_cuu_Thu_ChiAsync(string Ten, string Ngay, string So_tien, string Loai_Thu_Chi) {
            return base.Channel.Tra_cuu_Thu_ChiAsync(Ten, Ngay, So_tien, Loai_Thu_Chi);
        }
        
        public int[] Lay_Tat_ca_Cac_Nam() {
            return base.Channel.Lay_Tat_ca_Cac_Nam();
        }
        
        public System.Threading.Tasks.Task<int[]> Lay_Tat_ca_Cac_NamAsync() {
            return base.Channel.Lay_Tat_ca_Cac_NamAsync();
        }
        
        public int[] Thong_ke_Tong_Quat(string Thang, string Nam) {
            return base.Channel.Thong_ke_Tong_Quat(Thang, Nam);
        }
        
        public System.Threading.Tasks.Task<int[]> Thong_ke_Tong_QuatAsync(string Thang, string Nam) {
            return base.Channel.Thong_ke_Tong_QuatAsync(Thang, Nam);
        }
        
        public string[] Lay_danh_Sach_Ten() {
            return base.Channel.Lay_danh_Sach_Ten();
        }
        
        public System.Threading.Tasks.Task<string[]> Lay_danh_Sach_TenAsync() {
            return base.Channel.Lay_danh_Sach_TenAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QLCT_GIA_DINH.GD_Service.Lay_AnhResponse QLCT_GIA_DINH.GD_Service.GiaDinhServiceSoap.Lay_Anh(QLCT_GIA_DINH.GD_Service.Lay_AnhRequest request) {
            return base.Channel.Lay_Anh(request);
        }
        
        public byte[] Lay_Anh(string Ten_Hinh_anh) {
            QLCT_GIA_DINH.GD_Service.Lay_AnhRequest inValue = new QLCT_GIA_DINH.GD_Service.Lay_AnhRequest();
            inValue.Ten_Hinh_anh = Ten_Hinh_anh;
            QLCT_GIA_DINH.GD_Service.Lay_AnhResponse retVal = ((QLCT_GIA_DINH.GD_Service.GiaDinhServiceSoap)(this)).Lay_Anh(inValue);
            return retVal.Lay_AnhResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QLCT_GIA_DINH.GD_Service.Lay_AnhResponse> QLCT_GIA_DINH.GD_Service.GiaDinhServiceSoap.Lay_AnhAsync(QLCT_GIA_DINH.GD_Service.Lay_AnhRequest request) {
            return base.Channel.Lay_AnhAsync(request);
        }
        
        public System.Threading.Tasks.Task<QLCT_GIA_DINH.GD_Service.Lay_AnhResponse> Lay_AnhAsync(string Ten_Hinh_anh) {
            QLCT_GIA_DINH.GD_Service.Lay_AnhRequest inValue = new QLCT_GIA_DINH.GD_Service.Lay_AnhRequest();
            inValue.Ten_Hinh_anh = Ten_Hinh_anh;
            return ((QLCT_GIA_DINH.GD_Service.GiaDinhServiceSoap)(this)).Lay_AnhAsync(inValue);
        }
        
        public int ID_Gia_dinh_Tu_tang() {
            return base.Channel.ID_Gia_dinh_Tu_tang();
        }
        
        public System.Threading.Tasks.Task<int> ID_Gia_dinh_Tu_tangAsync() {
            return base.Channel.ID_Gia_dinh_Tu_tangAsync();
        }
        
        public string Lay_ID_Gia_dinh(string Ten_Gia_dinh) {
            return base.Channel.Lay_ID_Gia_dinh(Ten_Gia_dinh);
        }
        
        public System.Threading.Tasks.Task<string> Lay_ID_Gia_dinhAsync(string Ten_Gia_dinh) {
            return base.Channel.Lay_ID_Gia_dinhAsync(Ten_Gia_dinh);
        }
    }
}
